CREATE TABLE Member (
	MKEY NUMBER NOT NULL,
	MID VARCHAR2(100),
	MPASS VARCHAR2(100),
	MNAME VARCHAR2(30),
	MEMAIL VARCHAR2(100),
	phonenum varchar2(50),
	MREG varchar2(50),
	nickname varchar2(100),
	MGENDER varchar2(10),
	MMANIAQUOT NUMBER,
	MJOINDATE DATE,
	MAUTHNUM NUMBER,
	MCASH NUMBER,
	MPOINT NUMBER,
	MLEVEL NUMBER,
	MEMAILWHETHER CHAR(2),
	MADDRESS VARCHAR2(100),
	MSTATE CHAR(10),
	MBLOCKLIST VARCHAR2(100),
	MSELLERRATE FLOAT,
	MGIFTLEVEL NUMBER,
	MUNDERFIFTEEN CHAR(2),
	MGIFTDONECNT NUMBER,
	MMYGIFT VARCHAR2(200),
	MIP VARCHAR2(50),
	CONSTRAINT MEMBER_PK PRIMARY KEY (MKEY)
);

SELECT * FROM MEMBER;

DELETE FROM MEMBER
WHERE mkey = 4;

DROP TABLE MEMBER;

SELECT *
FROM MEMBER
WHERE mid='himan'
AND mpass='7777';
